### ISSUE TITLE
 Data too long for column 'DESCRIPTION' at row 1

### ISSUE THREAD

**Issue by jsmadja** [jsmadja/fluxx#4]
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'DESCRIPTION' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3564)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3498)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2113)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2568)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2113)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2409)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2327)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2312)
        at com.sun.gjc.spi.base.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:108)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:792)
        ... 71 more

**Comment by jsmadja** [comment]
Colonne DESCRIPTION de la table ITEM fixée à LONGTEXT
